---
title: "PUBPOL 543 Assingment 2 workbook"
output: html_notebook
---

Packages
```{r}
library(tidyverse)
library(ggplot2)
library(scales)
library(ggthemes)
library(magrittr)
library(rio)
library(pivottabler)
```

Data
```{r}
link = "https://github.com/Charting-Chumps/Data/raw/main/Race_Enrollment.csv"
df = as.data.frame(import(link))
```

Analysis
```{r}
df=as.data.frame(df)
df$Race=as.factor(df$Race)
df$SchoolYear=as.factor(df$SchoolYear)
df$Total=as.integer(df$Total)
df$YearTotal = c(1091355, 1091355, 1091355, 1091355, 1091355, 1091355, 1091355, 1088758, 1088758, 1088758, 1088758, 1088758, 1088758, 1088758, 1140997, 1140997, 1140997, 1140997, 1140997, 1140997, 1140997, 1133507, 1133507, 1133507, 1133507, 1133507, 1133507, 1133507, 1126191, 1126191, 1126191, 1126191, 1126191, 1126191, 1126191, 1113069, 1113069, 1113069, 1113069, 1113069, 1113069, 1113069, 1096921, 1096921, 1096921, 1096921, 1096921, 1096921, 1096921, 1082279, 1082279, 1082279, 1082279, 1082279, 1082279, 1082279)
df$PctTotalYear = df$Total / df$YearTotal
```

```{r}
base=ggplot(data=df,
            aes(x = SchoolYear,
                y = PctTotalYear,
                fill=reorder(Race,PctTotalYear)))
plot1=base + geom_bar(stat = 'identity',
                      position = 'stack') + 
      labs(title="Washington public schools are increasingly home to students of color",
                     x ="School Year", 
                     y = "Students",
                     caption = "Source: Washington State Department of Education") + 
      theme(plot.caption = element_text(hjust = 0, size = 8), 
                      plot.title = element_text(hjust = 0.5, size = 10), axis.title = element_text(size = 10)) + 
      scale_y_continuous(labels = percent) + 
      guides(fill=guide_legend(title="Race/Ethnicity"))
plot2 = plot1 + geom_hline(yintercept = 0.5, #where
                           size=0.5, #thickness
                           alpha=0.7,#transparency
                           color = "black", 
                           linetype = "dashed")
#plot3 = plot2 + geom_text(size = 3, 
                  #position = position_stack(vjust = 0.5),
                 # aes(label=percent(PctTotalYear,accuracy = 1)))
plot2
```

